In [4]:
class Employee:
    total_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.total_employees += 1

    def average_salary(self, employee_list):
        total_salary = 0
        for e in employee_list:
            total_salary += e.salary
        return total_salary / len(employee_list)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

# Creating instances of Employee and FulltimeEmployee classes
employee1 = Employee("John Doe", "Family A", 60000, "HR")
employee2 = Employee("Jane Smith", "Family B", 55000, "IT")
fulltime_employee1 = FulltimeEmployee("Alice Johnson", "Family C", 70000, "Finance")

# Calling member functions
employees = [employee1, employee2, fulltime_employee1]
avg_salary = employee1.average_salary(employees)
print(f"Average salary: ${avg_salary:.2f}")
print(f"Total employees: {Employee.total_employees}")

Average salary: $61666.67
Total employees: 3


2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)

In [6]:
import numpy as np


random_vector = np.random.uniform(1, 20, size=20)

print("original vector : ",random_vector)

reshaped_array = random_vector.reshape(4, 5)


reshaped_array[np.arange(reshaped_array.shape[0]), np.argmax(reshaped_array, axis=1)] = 0

print("Original reshaped array:")
print(reshaped_array)

original vector :  [17.81801116 16.7355839   8.87269919 10.75115033 12.58943498 15.37278419
 15.19414489 13.19438406 19.9733516  17.71361628  3.6067258   3.30342352
  6.45772366  7.14111965 17.95452976  3.84396699 18.71137074 16.27289234
 12.56125209  7.96704034]
Original reshaped array:
[[ 0.         16.7355839   8.87269919 10.75115033 12.58943498]
 [15.37278419 15.19414489 13.19438406  0.         17.71361628]
 [ 3.6067258   3.30342352  6.45772366  7.14111965  0.        ]
 [ 3.84396699  0.         16.27289234 12.56125209  7.96704034]]
